### ISSUE TITLE
Text Tool

### ISSUE THREAD

**Issue by SankalpPro** [JonComo/anim#1]
I am on windows and I can not use the text tool properly whenever I select the text tool it allows me to enter text properly for the first time but for the second time it does not working...

**Comment by JonComo** [comment]
Ah, I havn't tested on windows but I do have a windows machine. Give me a few days to get to it and see what the issue could possibly be. If you figure it out let me know and we could merge a change. Thanks for the heads up!

**Comment by JonComo** [comment]
@SankalpPro I tried entering text in multiple text boxes on windows, it seems to be working. You have to click to add a text box then write some text. Not seeing the issue currently.
