### ISSUE TITLE
Guide for downloading and running the code

### ISSUE THREAD

**Issue by JonComo** [JonComo/anim#107]
Hey @catruge you've been amazing with all these improvements! Coming back to the project I'm thinking we should have instructions on how to run anim after downloading it? I know you set something up so that it builds a release and gives us just a simple js file and index correct? Perhaps we could link that download in the readme. Also we should probably link to the github pages site so people can play with it easily once getting to the repo. Let me know your thoughts and thanks again for your massive contributions! 🌟 🌟 🌟 🌟 🌟

**Comment by catruge** [comment]
Hi @JonComo.

> Hey @catruge you've been amazing with all these improvements!

Thanks!

It does seem like a good idea to add instructions in. I created a pull request (#108) with some quick ones that link to the GitHub Pages site and explain how to run `anim` offline. What are your suggestions?

**Comment by JonComo** [comment]
@catruge This looks perfect, exactly what I was looking for thanks!
