### ISSUE TITLE
Math.js package eval error

### ISSUE THREAD

**Issue by catruge** [JonComo/anim#22]
Hello. I noticed that it's not possible to draw the farmer, dog nor computer (and possibly more) after setting up Webpack. I tracked it down to the new Math.js package that I installed while setting up Webpack. I haven't looked into it yet, but wanted to mention this problem. I created a pull request (#21) that should fix things for now by using the original `math.js`, although this shouldn't be considered a permanent solution.

**Comment by catruge** [comment]
I created a pull request (#28) that uses a Math.js 3.10.0 compatible version. It seems to be working for me, and for now, it's a better solution than #21.

**Comment by JonComo** [comment]
Looks good, I'll merge your fix!
