### ISSUE TITLE
README must be updated for NPM and Webpack instructions

### ISSUE THREAD

**Issue by catruge** [JonComo/anim#26]
Currently, the README doesn't really explain how to start using `anim`. Since Webpack has been set up, it might be hard to guess how to run or develop `anim` on personal systems. The README could list the required software (Node.js and NPM) for development and also how to set up the environment. It could also describe how to use the GitHub Sites version. If GitHub Releases are also set up, the README could explain how to download them and run `anim`.

**Comment by catruge** [comment]
I created a draft pull request (#27) with some proposed additions to the README.

**Comment by SankalpMe** [comment]
Great

**Comment by JonComo** [comment]
Looking good now!
