### ISSUE TITLE
Updating the version

### ISSUE THREAD

**Issue by catruge** [JonComo/anim#29]
Hello. It might be a good idea to update the version number shown in the `anim` webpage and also the one in the `package.json` field to match. Then, they could be incremented for every modification or addition, maybe using [semantic versioning](https://semver.org/). This way, it will be evident when breaking changes and bugfixes are made.

**Comment by JonComo** [comment]
If you'd like to describe your versioning system here I'd be happy to merge those changes in. Right now I see ver: 0.1 on the webpage and 1.0.0 in package.json

**Comment by catruge** [comment]
@JonComo, thanks. I'll try finding a way to reflect the version in `package.json` in the code. If I can't, then I'll just make a pull request with the version hardcoded.

**Comment by catruge** [comment]
Hi @JonComo. I've made my changes to the `resources.js` pull request (#30) since they seemed relevant (and also because it was simpler that way :smirk:). The version on the left side of the screen should now show the one defined in `package.json`:
![2021-02-28_09-46](https://user-images.githubusercontent.com/49883288/109739361-7f3e4e80-7b97-11eb-8896-e8cc052e9672.png)

This way, the version won't have to be continually recoded into the label.
