### ISSUE TITLE
slide issue

### ISSUE THREAD

**Issue by virtualdvid** [JonComo/anim#3]
Amazing tool! I just have started of using this tool on windows and I had several problem with the slide command. It worked just once since then it's been locked, how can I fix that?

**Comment by virtualdvid** [comment]
Never mind, I got it!

**Comment by JonComo** [comment]
@virtualdvid Glad it's working! 👍

**Comment by samyem** [comment]
Do not think slide is working as is deployed at https://joncomo.github.io/anim/ with windows and chrome
