### ISSUE TITLE
Changed axis

### ISSUE THREAD

**Issue by virtualdvid** [JonComo/anim#4]
Hi, I was working in your online version, and since your last update the axis changed to show `y, z` instead of the traditional `x, y`. Was it intentional?

**Comment by JonComo** [comment]
Yeah, sorry for the confusion, I should add more detailed comments with the commits. I just committed some more changes that add a "view xy" button in the menu. If you click that it will rotate the axes to the standard xy. Remember all points are still [x,y,z] as before.
