### ISSUE TITLE
ccapture.js-npmfixed not working

### ISSUE THREAD

**Issue by catruge** [JonComo/anim#42]
Hello. I noticed that `ccapture.js-npmfixed` is not importing properly and is acting the same as `ccapture.js`. I thought that I had tested it, but I probably made a mistake. I think that I found a solution using the original `ccapture.js`, but want to test it to make sure it actually works.

**Comment by JonComo** [comment]
I'm having an issue running npm start, I get this error:

> anim@1.0.0 start /Users/joncomo/Documents/anim
> webpack serve --open --config webpack.dev.js

/Users/joncomo/Documents/anim/node_modules/webpack/bin/webpack.js:85
	let packageManager;
	^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by catruge** [comment]
Hi @JonComo. This probably happened because you have an old version of Node.js installed that only supports the ES6 syntax in strict mode. Alongside it, you probably have a newer version of NPM. That's why it's returning
```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

If possible, Node.js should be updated to a later version.

**Comment by catruge** [comment]
**UPDATE:** I created a pull request (#43) that should fix the `ccapture.js` error. `ccapture.js-npmfixed` is necessary for `webm` and `gif` exports though, so I kept that package.
