### ISSUE TITLE
Event.prototype.srcElement is deprecated

### ISSUE THREAD

**Issue by catruge** [JonComo/anim#53]
Hello. I wanted to mention that `Event.prototype.srcElement` is deprecated and `Event.prototype.target` should be used now.

**Comment by JonComo** [comment]
Is it a simple swap?

**Comment by catruge** [comment]
@JonComo, I checked, and it seems to be so.

**Comment by catruge** [comment]
I wanted to mention that I created a pull request that should use `target` instead of `srcElement` in the code (#58).
