### ISSUE TITLE
Synchronise GitHub Releases and Pages

### ISSUE THREAD

**Issue by catruge** [JonComo/anim#82]
When any commit is pushed to the `master` branch, the GitHub Pages workflow deploys it. However, releases are not created this frequently. It might be a good idea to tag commits in the workflow. The problem is that there might exist commits between releases which would be released. A possible fix would be to create a `dev` branch that is merged into `master` every time a release is intended. Afterwards, a release can be manually created from the tag and notes can be added as needed. @JonComo, what are your thoughts on this?

**Comment by catruge** [comment]
I updated #83 so that it only tags builds and redeploys to GitHub Pages when the version number changes. This eliminates the need for a `dev` branch.

**Comment by JonComo** [comment]
@catruge That sounds like a great solution! Thanks
