### ISSUE TITLE
Delete button does not work in text box

### ISSUE THREAD

**Issue by AkashKarnatak** [JonComo/anim#9]

**Comment by JonComo** [comment]
What OS are you running? Thanks for finding this issue! I have only tested anim on a mac laptop.

**Comment by AkashKarnatak** [comment]
I am using Ubuntu 18.04, I have tried it on both Firefox and Google Chrome.

**Comment by JonComo** [comment]
Hmm, I have a desktop system with ubuntu but no monitor or keyboard currently. Do you know javascript? If you locate the issue I'll merge your code changes.

**Comment by AkashKarnatak** [comment]
I am beginner in javascript and I am still learning. When I get comfortable with it, I'll surely contribute to this project.

**Comment by catruge** [comment]
Hello. I also encountered this problem. I think the reason is just that there's no <kbd>Delete</kbd> condition for the text box. I created a pull request with a fix (#16) and it seems to be working on my system.

**Comment by JonComo** [comment]
Merged
